// OneToMany/onetomany-angular/src/app/weather-forecast/weather-forecast.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface Forecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string;
}

@Component({
  selector: 'app-weather-forecast',
  templateUrl: './weather-forecast.component.html',
  styleUrls: ['./weather-forecast.component.css']
})
export class WeatherForecastComponent implements OnInit {
  forecasts: Forecast[] = [];
  loading = false;
  error: string | null = null;

  sortColumn: keyof Forecast | '' = '';
  sortDirection: 'asc' | 'desc' = 'asc';

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.loadForecast();
  }

  loadForecast() {
    this.loading = true;
    this.error = null;
    this.http.get<Forecast[]>('https://localhost:7226/WeatherForecast')
      .subscribe({
        next: data => {
          this.forecasts = data;
          if (this.sortColumn) {
            this.sortTable(this.sortColumn);
          }
          this.loading = false;
        },
        error: () => {
          this.error = 'Error loading data';
          this.loading = false;
        }
      });
  }

  sortTable(column: keyof Forecast) {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.forecasts = [...this.forecasts].sort((a, b) => {
      if (a[column] < b[column]) return this.sortDirection === 'asc' ? -1 : 1;
      if (a[column] > b[column]) return this.sortDirection === 'asc' ? 1 : -1;
      return 0;
    });
  }
}
<div class="container mt-4">
  <h2>Weather Forecast</h2>
  <button class="btn btn-primary mb-3" (click)="loadForecast()" [disabled]="loading">
    Reload
    <span *ngIf="loading" class="spinner-border spinner-border-sm ms-2"></span>
  </button>

  <div *ngIf="loading && !error" class="mb-3">
    <span class="spinner-border spinner-border-sm"></span> Loading...
  </div>
  <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

  <table *ngIf="forecasts.length && !loading" class="table table-striped">
    <thead>
        <p>Click on the column headers to sort the table</p>
      <tr>
        <th (click)="sortTable('date')" style="cursor:pointer">
          Date
          <span *ngIf="sortColumn === 'date'">
            {{ sortDirection === 'asc' ? '▲' : '▼' }}
          </span>
        </th>
        <th (click)="sortTable('temperatureC')" style="cursor:pointer">
          Temp (°C)
          <span *ngIf="sortColumn === 'temperatureC'">
            {{ sortDirection === 'asc' ? '▲' : '▼' }}
          </span>
        </th>
        <th (click)="sortTable('temperatureF')" style="cursor:pointer">
          Temp (°F)
          <span *ngIf="sortColumn === 'temperatureF'">
            {{ sortDirection === 'asc' ? '▲' : '▼' }}
          </span>
        </th>
        <th (click)="sortTable('summary')" style="cursor:pointer">
          Summary
          <span *ngIf="sortColumn === 'summary'">
            {{ sortDirection === 'asc' ? '▲' : '▼' }}
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let forecast of forecasts">
        <td>{{ forecast.date | date:'mediumDate' }}</td>
        <td>{{ forecast.temperatureC }}</td>
        <td>{{ forecast.temperatureF }}</td>
        <td>{{ forecast.summary }}</td>
      </tr>
    </tbody>
  </table>
</div>

// OneToMany/onetomany-reactjs/src/pages/WeatherForecast.jsx
import React, { useEffect, useState } from "react";

const WEATHER_API_URL = "https://localhost:7226/WeatherForecast";

const columns = [
  { key: "date", label: "Date" },
  { key: "temperatureC", label: "Temp (°C)" },
  { key: "temperatureF", label: "Temp (°F)" },
  { key: "summary", label: "Summary" },
];

export default function WeatherForecast() {
  const [forecasts, setForecasts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [sortConfig, setSortConfig] = useState({ key: "date", direction: "asc" });

  const fetchWeather = async () => {
    setLoading(true);
    setError("");
    try {
      const response = await fetch(WEATHER_API_URL, {
        headers: { accept: "text/plain" },
      });
      if (!response.ok) throw new Error("Failed to fetch");
      const data = await response.json();
      setForecasts(data);
    } catch (err) {
      setError("Error loading weather data.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchWeather();
  }, []);

  const sortedForecasts = React.useMemo(() => {
    if (!sortConfig.key) return forecasts;
    const sorted = [...forecasts].sort((a, b) => {
      if (a[sortConfig.key] < b[sortConfig.key]) return sortConfig.direction === "asc" ? -1 : 1;
      if (a[sortConfig.key] > b[sortConfig.key]) return sortConfig.direction === "asc" ? 1 : -1;
      return 0;
    });
    return sorted;
  }, [forecasts, sortConfig]);

  const handleSort = (key) => {
    setSortConfig((prev) => {
      if (prev.key === key) {
        return { key, direction: prev.direction === "asc" ? "desc" : "asc" };
      }
      return { key, direction: "asc" };
    });
  };

  const getSortIndicator = (key) => {
    if (sortConfig.key !== key) return "";
    return sortConfig.direction === "asc" ? " ▲" : " ▼";
  };

  return (
    <div className="main-content">
      <h2>Weather Forecast</h2>
      <div className="mb-2 text-muted" style={{ fontSize: "0.95em" }}>
        Note: Click on any column header to sort the table.
      </div>
      <button className="btn btn-primary mb-3" onClick={fetchWeather} disabled={loading}>
        {loading ? "Loading..." : "Reload"}
      </button>
      {error && <div className="alert alert-danger">{error}</div>}
      <table className="table table-striped">
        <thead>
          <tr>
            {columns.map((col) => (
              <th
                key={col.key}
                style={{ cursor: "pointer", userSelect: "none" }}
                onClick={() => handleSort(col.key)}
              >
                {col.label}
                {getSortIndicator(col.key)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sortedForecasts.map((f, idx) => (
            <tr key={idx}>
              <td>{f.date}</td>
              <td>{f.temperatureC}</td>
              <td>{f.temperatureF}</td>
              <td>{f.summary}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
