// OneToMany/onetomany-angular/src/app/zoo/zoo.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface Bird {
  id: number;
  birdName: string;
  zooId: number;
  zoo?: any;
}

interface Zoo {
  id: number;
  nameOfZoo: string;
  locationOfZoo: string;
  birds: any[];
}

@Component({
  selector: 'app-zoo',
  templateUrl: './zoo.component.html',
  styleUrls: ['./zoo.component.css']
})
export class ZooComponent {
  zoos: Zoo[] = [];
  birds: Bird[] = [];
  loading = false;
  error: string | null = null;

  nameOfZoo = '';
  locationOfZoo = '';

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.getZoos();
    this.getBirds();
  }

  getZoos() {
    this.loading = true;
    this.error = null;
    this.http.get<Zoo[]>('https://localhost:7226/api/Practice/GetZoos')
      .subscribe({
        next: data => {
          this.zoos = data;
          this.loading = false;
        },
        error: () => {
          this.error = 'Error loading zoos';
          this.loading = false;
        }
      });
  }

  getBirds() {
    this.http.get<Bird[]>('https://localhost:7226/api/Practice/GetBirds')
      .subscribe({
        next: data => {
          this.birds = data;
        },
        error: () => {
          this.error = 'Error loading birds';
        }
      });
  }

  createZoo() {
    if (!this.nameOfZoo || !this.locationOfZoo) return;
    this.loading = true;
    this.error = null;
    this.http.post<Zoo>('https://localhost:7226/api/Practice/CreateZoo', {
      nameOfZoo: this.nameOfZoo,
      locationOfZoo: this.locationOfZoo
    }).subscribe({
      next: zoo => {
        this.zoos.push(zoo);
        this.nameOfZoo = '';
        this.locationOfZoo = '';
        this.loading = false;
      },
      error: () => {
        this.error = 'Error creating zoo';
        this.loading = false;
      }
    });
  }

  getBirdsForZoo(zooId: number): Bird[] {
    return this.birds.filter(bird => bird.zooId === zooId);
  }
}
<div class="container mt-4">
  <h2>Zoo Management</h2>

  <form class="row g-3 mb-4" (ngSubmit)="createZoo()">
    <div class="col-md-5">
      <input type="text" class="form-control" placeholder="Zoo Name" [(ngModel)]="nameOfZoo" name="nameOfZoo" required>
    </div>
    <div class="col-md-5">
      <input type="text" class="form-control" placeholder="Location" [(ngModel)]="locationOfZoo" name="locationOfZoo" required>
    </div>
    <div class="col-md-2">
      <button class="btn btn-success w-100" type="submit" [disabled]="loading">Create Zoo</button>
    </div>
  </form>

  <button class="btn btn-primary mb-3" (click)="getZoos(); getBirds()" [disabled]="loading">
    Load Zoos & Birds
    <span *ngIf="loading" class="spinner-border spinner-border-sm ms-2"></span>
  </button>

  <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

  <table *ngIf="zoos.length" class="table table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Location</th>
        <th>Birds</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let zoo of zoos">
        <td>{{ zoo.id }}</td>
        <td>{{ zoo.nameOfZoo }}</td>
        <td>{{ zoo.locationOfZoo }}</td>
        <td>
          <ul *ngIf="getBirdsForZoo(zoo.id).length; else noBirds">
            <li *ngFor="let bird of getBirdsForZoo(zoo.id)">
              {{ bird.birdName }}
            </li>
          </ul>
          <ng-template #noBirds>
            <span>No birds</span>
          </ng-template>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// OneToMany/onetomany-reactjs/src/pages/Zoo.jsx
import React, { useEffect, useState } from "react";

const GET_ZOOS_URL = "https://localhost:7226/api/Practice/GetZoos";
const CREATE_ZOO_URL = "https://localhost:7226/api/Practice/CreateZoo";

export default function Zoo() {
  const [zoos, setZoos] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState({ nameOfZoo: "", locationOfZoo: "" });
  const [creating, setCreating] = useState(false);

  const fetchZoos = async () => {
    setLoading(true);
    setError("");
    try {
      const response = await fetch(GET_ZOOS_URL, {
        headers: { accept: "text/plain" },
      });
      if (!response.ok) throw new Error("Failed to fetch zoos");
      const data = await response.json();
      setZoos(data);
    } catch (err) {
      setError("Error loading zoos.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchZoos();
  }, []);

  const handleInputChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleCreateZoo = async (e) => {
    e.preventDefault();
    setCreating(true);
    setError("");
    try {
      const response = await fetch(CREATE_ZOO_URL, {
        method: "POST",
        headers: {
          accept: "text/plain",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(form),
      });
      if (!response.ok) throw new Error("Failed to create zoo");
      await response.json();
      setForm({ nameOfZoo: "", locationOfZoo: "" });
      fetchZoos();
    } catch (err) {
      setError("Error creating zoo.");
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="main-content">
      <h2>Zoo Page</h2>
      <form className="mb-4" onSubmit={handleCreateZoo}>
        <div className="mb-2">
          <label className="form-label">Name of Zoo</label>
          <input
            type="text"
            name="nameOfZoo"
            className="form-control"
            value={form.nameOfZoo}
            onChange={handleInputChange}
            required
          />
        </div>
        <div className="mb-2">
          <label className="form-label">Location of Zoo</label>
          <input
            type="text"
            name="locationOfZoo"
            className="form-control"
            value={form.locationOfZoo}
            onChange={handleInputChange}
            required
          />
        </div>
        <button className="btn btn-success" type="submit" disabled={creating}>
          {creating ? "Creating..." : "Create Zoo"}
        </button>
      </form>
      <button className="btn btn-primary mb-3" onClick={fetchZoos} disabled={loading}>
        {loading ? "Loading..." : "Reload Zoos"}
      </button>
      {error && <div className="alert alert-danger">{error}</div>}
      <table className="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name of Zoo</th>
            <th>Location</th>
          </tr>
        </thead>
        <tbody>
          {zoos.map((zoo) => (
            <tr key={zoo.id}>
              <td>{zoo.id}</td>
              <td>{zoo.nameOfZoo}</td>
              <td>{zoo.locationOfZoo}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {zoos.length === 0 && !loading && <div>No zoos found.</div>}
    </div>
  );
}
