// OneToMany/onetomany-reactjs/src/components/Navbar.jsx
import React from 'react';
import { Navbar, Nav, Container } from 'react-bootstrap';
import { Link } from 'react-router-dom'; // Add this import

export default function AppNavbar() {
  return (
    <Navbar expand="lg" className="custom-navbar shadow-sm" variant="dark">
      <Container>
        <Navbar.Brand as={Link} to="/" className="fw-bold text-white">
          <img
            src="/vite.svg"
            alt="Logo"
            width="32"
            height="32"
            className="me-2"
          />
          React 18.x Journey
        </Navbar.Brand>
        <Navbar.Toggle aria-controls="main-navbar-nav" />
        <Navbar.Collapse id="main-navbar-nav">
          <Nav className="ms-auto">
            <Nav.Link as={Link} to="/" className="text-white">Home</Nav.Link>
            <Nav.Link as={Link} to="/weather" className="text-white">Weather Forecast</Nav.Link>
            <Nav.Link as={Link} to="/bird" className="text-white">Bird</Nav.Link>
            <Nav.Link as={Link} to="/zoo" className="text-white">Zoo</Nav.Link>
            <Nav.Link as={Link} to="/about" className="text-white">About</Nav.Link>
            <Nav.Link as={Link} to="/contact" className="text-white">Contact</Nav.Link>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
  );
}

// OneToMany/onetomany-angular/src/app/navbar/navbar.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  @ViewChild('navbarNav', { static: false }) navbarNav!: ElementRef;

  collapseNavbar() {
    const navbar = this.navbarNav.nativeElement;
    if (navbar.classList.contains('show')) {
      // Bootstrap 5 uses Collapse from bootstrap JS
      // @ts-ignore
      const collapse = bootstrap.Collapse.getInstance(navbar) || new bootstrap.Collapse(navbar);
      collapse.hide();
    }
  }
}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand fw-bold" routerLink="/">Angular Hello World</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav" #navbarNav>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" (click)="collapseNavbar()">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/weather-forecast">Weather Forecast</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/zoo">Zoo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/birds">Birds</a>
        </li>        
        <li class="nav-item">
          <a class="nav-link" routerLink="/about" routerLinkActive="active" (click)="collapseNavbar()">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/contact" routerLinkActive="active" (click)="collapseNavbar()">Contact Me</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
